const QueryData = [
  {
    _id: "1",
    upVotes: 3,
    downVotes: 2,
    noOfAnswers: 2,
    userId: 1,
    author: "Sudhanshu Panthri",
    queryTitle: "What is React ?",
    queryBody: "Lorem Ipsium",
    answer: [
      {
        answerBody: "I am not sure but i guess it's a frontend Framework",
        userAnswered: "sam",
        answeredOn: "May 27",
        userId: 2,
      },
      {
        answerBody: "React is a frontend Framework developed by Meta",
        userAnswered: "Arav",
        answeredOn: "June 16",
        userId: 3,
      },
    ],
    askedOn: "May 26",
    tags: ["react", "javascript", "frontend"],
  },
  {
    _id: "2",
    upVotes: 3,
    downVotes: 2,
    noOfAnswers: 2,
    userId: 1,
    author: "Sudhanshu Panthri",
    queryTitle: "What is React ?",
    queryBody: "Lorem Ipsium",
    answer: [
      {
        answerBody: "answer",
        userAnswered: "sam",
        answeredOn: "May 27",
        userId: 2,
      },
    ],
    askedOn: "May 26",
    tags: ["react", "javascript", "frontend"],
  },
  {
    _id: "3",
    upVotes: 3,
    downVotes: 2,
    noOfAnswers: 2,
    userId: 1,
    author: "Sudhanshu Panthri",
    queryTitle: "What is React ?",
    queryBody: "Lorem Ipsium",
    answer: [
      {
        answerBody: "answer",
        userAnswered: "sam",
        answeredOn: "May 27",
        userId: 2,
      },
    ],
    askedOn: "May 26",
    tags: ["react", "javascript", "frontend"],
  },
  {
    _id: "4",
    upVotes: 3,
    downVotes: 2,
    noOfAnswers: 2,
    userId: 1,
    author: "Sudhanshu Panthri",
    queryTitle: "What is React ?",
    queryBody: "Lorem Ipsium",
    answer: [
      {
        answerBody: "answer",
        userAnswered: "sam",
        answeredOn: "May 27",
        userId: 2,
      },
    ],
    askedOn: "May 26",
    tags: ["react", "javascript", "frontend"],
  },
  {
    _id: "5",
    upVotes: 3,
    downVotes: 2,
    noOfAnswers: 2,
    userId: 1,
    author: "Sudhanshu Panthri",
    queryTitle: "What is React ?",
    queryBody: "Lorem Ipsium",
    answer: [
      {
        answerBody: "React is a frontend framework developed by Meta.",
        userAnswered: "sam",
        answeredOn: "May 27",
        userId: 2,
      },
    ],
    askedOn: "May 26",
    tags: ["react", "javascript", "frontend"],
  },
  {
    _id: "6",
    upVotes: 3,
    downVotes: 2,
    noOfAnswers: 2,
    userId: 1,
    author: "Sudhanshu Panthri",
    queryTitle: "What is React ?",
    queryBody: "Lorem Ipsium",
    answer: [
      {
        answerBody: "answer",
        userAnswered: "sam",
        answeredOn: "May 27",
        userId: 2,
      },
    ],
    askedOn: "May 26",
    tags: ["react", "javascript", "frontend"],
  },
];

export default QueryData;
